# Usar una imagen base de Node.js
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Construir la aplicación
RUN npm run build

# Instalar el servidor web nginx para servir la app
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Exponer el puerto
EXPOSE 80

# Comando para correr el servidor web
CMD ["nginx", "-g", "daemon off;"]
